package NuGet_Kotlin_Miruken.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = '18499CBF-CC08-47D3-92D5-E4B9C09BD7B1PreReleaseVcsRoot' (id = 'NuGet_Kotlin_Miruken_MirukenMTSln_PreReleaseVCSRoot')
accordingly and delete the patch script.
*/
changeVcsRoot("18499CBF-CC08-47D3-92D5-E4B9C09BD7B1PreReleaseVcsRoot") {
    val expected = GitVcsRoot({
        uuid = "18499CBF-CC08-47D3-92D5-E4B9C09BD7B1PreReleaseVcsRoot"
        id = "NuGet_Kotlin_Miruken_MirukenMTSln_PreReleaseVCSRoot"
        name = "git@github.com:Miruken-DotNet/Miruken.MassTransit.git_PreRelease"
        url = "git@github.com:Miruken-DotNet/Miruken.MassTransit.git"
        branch = "%DefaultBranch%"
        branchSpec = "%BranchSpecification%"
        agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
        authMethod = uploadedKey {
            uploadedKey = "provenstyle"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "provenstyle"
            passphrase = ""
        }
    }

}
