package NuGet_Kotlin_Miruken.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532CIVcsRoot' (id = 'NuGet_Kotlin_Miruken_MirukenSln_CIVCSRoot')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532", GitVcsRoot({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532CIVcsRoot"
    id = "NuGet_Kotlin_Miruken_MirukenSln_CIVCSRoot"
    name = "git@github.com:Miruken-DotNet/Miruken.git_CI"
    url = "git@github.com:Miruken-DotNet/Miruken.git"
    branch = "%DefaultBranch%"
    branchSpec = "%BranchSpecification%"
    agentCleanPolicy = GitVcsRoot.AgentCleanPolicy.ALWAYS
    authMethod = uploadedKey {
        uploadedKey = "provenstyle"
    }
}))

