package NuGet_Kotlin_Miruken.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532TeamCityVcsRoot' (id = 'NuGet_Kotlin_Miruken_MirukenSln_TeamCityVCSRoot')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532", GitVcsRoot({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532TeamCityVcsRoot"
    id = "NuGet_Kotlin_Miruken_MirukenSln_TeamCityVCSRoot"
    name = "git@github.com:Miruken-DotNet/MirukenKotlinBuild.git_TeamCity"
    url = "git@github.com:Miruken-DotNet/MirukenKotlinBuild.git"
    authMethod = uploadedKey {
        uploadedKey = "provenstyle"
    }
}))

