package NuGet_Kotlin_Improving.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '1852e351-879e-426d-9bb7-299060589c6f' (id = 'NuGet_Kotlin_Improving_ImpHghwyDtScp')
accordingly and delete the patch script.
*/
changeProject("1852e351-879e-426d-9bb7-299060589c6f") {
    params {
        expect {
            param("PatchVersion", "0")
        }
        update {
            param("PatchVersion", "2")
        }
    }
}
