package NuGet_Kotlin_Miruken.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidate' (id = 'NuGet_Kotlin_Miruken_MirukenSln_MirukenValidate')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject", Project({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidate"
    id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidate"
    parentId = "NuGet_Kotlin_Miruken_MirukenSln_DeploymentProject"
    name = "Miruken.Validate"
    description = "Miruken.Validate nuget package"

    params {
        param("NuGetPackSpecFiles", """Source\Miruken.Validate\Miruken.Validate.nuspec""")
        param("PackageName", "Miruken.Validate")
    }
    buildTypesOrderIds = arrayListOf("NuGet_Kotlin_Miruken_MirukenSln_MirukenValidate_DeployPreRelease", "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidate_DeployRelease")
}))

