package NuGet_Kotlin_Miruken.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532' (id = 'NuGet_Kotlin_Miruken_MirukenSln')
in the project with uuid = 'eea6b38a-724a-4304-a454-3b6cfb93bfdb' and delete the patch script.
*/
create("eea6b38a-724a-4304-a454-3b6cfb93bfdb", Project({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532"
    id = "NuGet_Kotlin_Miruken_MirukenSln"
    parentId = "NuGet_Kotlin_Miruken"
    name = "Miruken Solution Kotlin"
    description = "CI/CD for Miruken.sln"

    params {
        param("ArtifactsIn", """
            Source      => Build.zip!/Source
            packages    => Build.zip!/packages
            Miruken.sln => Build.zip!
        """.trimIndent())
        param("ArtifactsOut", """
            Build.zip!/Source   => Source
            Build.zip!/packages => packages
            Build.zip!/Miruken.sln
        """.trimIndent())
        param("MajorVersion", "1")
        param("MinorVersion", "11")
        param("PatchVersion", "18")
        param("PreReleaseProjectId", "NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild")
        param("ReleaseProjectId", "NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild")
        param("Solution", "Miruken.sln")
        param("SolutionProjectId", "NuGet_Kotlin_Miruken_MirukenSln")
        param("TestAssemblies", """**\bin\*Test*.dll""")
    }
    buildTypesOrderIds = arrayListOf("NuGet_Kotlin_Miruken_MirukenSln_CIBuild", "NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild", "NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild")
    subProjectsOrder = arrayListOf("NuGet_Kotlin_Miruken_MirukenSln_DeploymentProject")
}))

