package NuGet_Kotlin_Miruken.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle' (id = 'NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject", Project({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle"
    id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle"
    parentId = "NuGet_Kotlin_Miruken_MirukenSln_DeploymentProject"
    name = "Miruken.Validate.Castle"
    description = "Miruken.Validate.Castle nuget package"

    params {
        param("NuGetPackSpecFiles", """Source\Miruken.Validate.Castle\Miruken.Validate.Castle.nuspec""")
        param("PackageName", "Miruken.Validate.Castle")
    }
    buildTypesOrderIds = arrayListOf("NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_DeployPreRelease", "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_DeployRelease")
}))

