package NuGet_Kotlin_Miruken.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenCastle' (id = 'NuGet_Kotlin_Miruken_MirukenSln_MirukenCastle')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_DeploymentProject", Project({
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenCastle"
    id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenCastle"
    parentId = "NuGet_Kotlin_Miruken_MirukenSln_DeploymentProject"
    name = "Miruken.Castle"
    description = "Miruken.Castle nuget package"

    params {
        param("NuGetPackSpecFiles", """Source\Miruken.Castle\Miruken.Castle.nuspec""")
        param("PackageName", "Miruken.Castle")
    }
    buildTypesOrderIds = arrayListOf("NuGet_Kotlin_Miruken_MirukenSln_MirukenCastle_DeployPreRelease", "NuGet_Kotlin_Miruken_MirukenSln_MirukenCastle_DeployRelease")
}))

