package NuGet_Kotlin_MirukenCore.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '7e62a1a9-b045-4f9c-be42-cb9a649441e1' (id = 'NuGet_Kotlin_MirukenCore_MirukenAspNet')
accordingly, and delete the patch script.
*/
changeProject(uuid("7e62a1a9-b045-4f9c-be42-cb9a649441e1")) {
    params {
        expect {
            param("PatchVersion", "1")
        }
        update {
            param("PatchVersion", "3")
        }
    }
}
