package NuGet_Kotlin_MirukenCore.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the project with uuid = '923b8dd0-4464-4d2d-a137-197ad679e5cd_MirukenCastle' (id = 'NuGet_Kotlin_MirukenCore_MirukenSln_MirukenCastle')
from your code, and delete the patch script.
*/
deleteProject(uuid("923b8dd0-4464-4d2d-a137-197ad679e5cd_MirukenCastle"))

