package NuGet_Kotlin_MirukenCore.patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '94b7f965-6df7-4b65-a2e2-82c47836991f' (id = 'NuGet_Kotlin_MirukenCore_MirukenQuartzSln')
accordingly, and delete the patch script.
*/
changeProject(uuid("94b7f965-6df7-4b65-a2e2-82c47836991f")) {
    params {
        expect {
            param("PatchVersion", "1")
        }
        update {
            param("PatchVersion", "2")
        }
    }
}
