package NuGet_Kotlin_MirukenCore.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.DotnetNugetPushStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dotnetNugetPush
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '923b8dd0-4464-4d2d-a137-197ad679e5cd_Miruken_DeployPreRelease' (id = 'NuGet_Kotlin_MirukenCore_MirukenSln_Miruken_DeployPreRelease')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("923b8dd0-4464-4d2d-a137-197ad679e5cd_Miruken_DeployPreRelease")) {
    params {
        add {
            param("ArtifactsOut", """
                Build.zip!/Source   => Source
                Build.zip!/Miruken.sln
            """.trimIndent())
        }
    }

    expectSteps {
        dotnetNugetPush {
            name = "Prerelease Nuget on TC Feed"
            packages = "Source/Miruken/bin/Miruken.%PackageVersion%.nupkg"
            serverUrl = "%teamcity.nuget.feed.guestAuth._Root.default.v2%"
            apiKey = "%teamcity.nuget.feed.api.key%"
            param("configuration", "Debug")
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
            param("outputDir", "nupkg")
            param("teamcity.build.workingDir", "/")
        }
    }
    steps {
        update<DotnetNugetPushStep>(0) {
            apiKey = "credentialsJSON:67fc8f44-f16c-456e-8d71-df4fcf9eceb2"
        }
    }
}
