package NuGet_Kotlin_MirukenCore.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dotnetNugetPush
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.nuGetPack
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '923b8dd0-4464-4d2d-a137-197ad679e5cd_Miruken_DeployPreRelease' (id = 'NuGet_Kotlin_MirukenCore_MirukenSln_Miruken_DeployPreRelease')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("923b8dd0-4464-4d2d-a137-197ad679e5cd_Miruken_DeployPreRelease")) {
    expectSteps {
        nuGetPack {
            name = "Prerelease Nuget on TC Feed"
            executionMode = BuildStep.ExecutionMode.RUN_ON_SUCCESS
            toolPath = "%teamcity.tool.NuGet.CommandLine.DEFAULT%"
            paths = "%NuGetPackSpecFiles%"
            preferProjectPaths = true
            version = "%PackageVersion%"
            outputDir = "nupkg"
            cleanOutputDir = true
            publishPackages = true
            param("toolPathSelector", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
        }
    }
    steps {
        insert(0) {
            dotnetNugetPush {
                name = "Prerelease Nuget on TC Feed (1)"
                packages = "Source/Miruken/bin/Miruken.%PackageVersion%.nupkg"
                serverUrl = "%teamcity.nuget.feed.guestAuth._Root.default.v2%"
                apiKey = "credentialsJSON:67fc8f44-f16c-456e-8d71-df4fcf9eceb2"
                param("outputDir", "nupkg")
                param("teamcity.build.workingDir", "/")
                param("configuration", "Debug")
                param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
            }
        }
        items.removeAt(1)
    }
}
