package NuGet_Kotlin_Miruken.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken_DeployRelease' (id = 'NuGet_Kotlin_Miruken_MirukenSln_Miruken_DeployRelease')
accordingly and delete the patch script.
*/
changeBuildType("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken_DeployRelease") {
    expectDisabledSettings("JetBrains.AssemblyInfo", "RUNNER_1", "RUNNER_2", "RUNNER_21", "RUNNER_22", "RUNNER_3", "RUNNER_4", "RUNNER_5", "RUNNER_8")
    updateDisabledSettings("JetBrains.AssemblyInfo", "RUNNER_1", "RUNNER_2", "RUNNER_21", "RUNNER_22", "RUNNER_3", "RUNNER_4", "RUNNER_5")
}
