package NuGet_Kotlin_Miruken.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken_DeployPreRelease' (id = 'NuGet_Kotlin_Miruken_MirukenSln_Miruken_DeployPreRelease')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken", BuildType({
    template = "StandardNuGetBuildTemplate"
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_Miruken_DeployPreRelease"
    id = "NuGet_Kotlin_Miruken_MirukenSln_Miruken_DeployPreRelease"
    name = "Deploy PreRelease"
    description = "This will push a NuGet package with a -PreRelease tag for testing from the develop branch. NO CI.   (Note: Non-prerelease nuget packages come from the master branch)"

    buildNumberPattern = "%BuildFormatSpecification%"

    params {
        param("BuildFormatSpecification", "%dep.NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild.BuildFormatSpecification%")
        param("PackageVersion", "%dep.NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild.PackageVersion%")
    }

    triggers {
        finishBuildTrigger {
            id = "NuGet_Kotlin_Miruken_MirukenSln_Miruken_DeployPreRelease_TRIGGER"
            buildTypeExtId = "NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild"
            successfulOnly = true
            branchFilter = "+:*"
        }
    }

    dependencies {
        dependency("NuGet_Kotlin_Miruken_MirukenSln_PreReleaseBuild") {
            snapshot {
            }

            artifacts {
                id = "NuGet_Kotlin_Miruken_MirukenSln_Miruken_PreRelease_ARTIFACT_DEPENDENCY"
                artifactRules = "%ArtifactsOut%"
            }
        }
    }
    
    disableSettings("JetBrains.AssemblyInfo", "RUNNER_1", "RUNNER_2", "RUNNER_21", "RUNNER_22", "RUNNER_3", "RUNNER_5", "RUNNER_6", "RUNNER_8")
}))

