package NuGet_Kotlin_Miruken.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_CIBuild' (id = 'NuGet_Kotlin_Miruken_MirukenSln_CIBuild')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532", BuildType({
    template = "StandardNuGetBuildTemplate"
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_CIBuild"
    id = "NuGet_Kotlin_Miruken_MirukenSln_CIBuild"
    name = "CI Build"
    description = "Watches git repo & creates a build for any change to any branch. Runs tests. Does NOT package/deploy NuGet packages!"

    buildNumberPattern = "%BuildFormatSpecification%"

    params {
        param("BranchSpecification", "+:refs/heads/(*)")
        param("MajorVersion", "0")
        param("MinorVersion", "0")
        param("PatchVersion", "0")
        param("PdbFilesForSymbols", "")
        param("PrereleaseVersion", "-CI.%build.counter%")
    }

    vcs {
        root("NuGet_Kotlin_Miruken_MirukenSln_CIVCSRoot")

        cleanCheckout = true
    }

    triggers {
        vcs {
            id = "NuGet_Kotlin_Miruken_MirukenSln_ci_vcsTrigger"
            quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_DEFAULT
            perCheckinTriggering = true
            groupCheckinsByCommitter = true
            enableQueueOptimization = false
        }
    }

    features {
        feature {
            id = "symbol-indexer"
            type = "symbol-indexer"
            enabled = false
        }
    }
    
    disableSettings("RUNNER_21", "RUNNER_22", "RUNNER_4", "RUNNER_5", "RUNNER_6", "RUNNER_8")
}))

