package NuGet_Kotlin_Miruken.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle_DeployRelease' (id = 'NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_DeployRelease')
in the project with uuid = '50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle' and delete the patch script.
*/
create("50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle", BuildType({
    template = "StandardNuGetBuildTemplate"
    uuid = "50fcdffb-6d49-43d4-a0fc-8e6dbc47a532_MirukenValidateCastle_DeployRelease"
    id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_DeployRelease"
    name = "Deploy Release"
    description = "This will push a NuGet package from the MASTER branch. NO CI."

    buildNumberPattern = "%BuildFormatSpecification%"

    params {
        param("BuildFormatSpecification", "%dep.NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild.BuildFormatSpecification%")
        param("PackageVersion", "%dep.NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild.PackageVersion%")
        param("PrereleaseVersion", "")
    }

    triggers {
        finishBuildTrigger {
            id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_Release_TRIGGER"
            buildTypeExtId = "NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild"
            branchFilter = "+:master"
        }
    }

    dependencies {
        dependency("NuGet_Kotlin_Miruken_MirukenSln_ReleaseBuild") {
            snapshot {
            }

            artifacts {
                id = "NuGet_Kotlin_Miruken_MirukenSln_MirukenValidateCastle_Release_ARTIFACT_DEPENDENCY"
                artifactRules = "%ArtifactsOut%"
            }
        }
    }
    
    disableSettings("JetBrains.AssemblyInfo", "RUNNER_1", "RUNNER_2", "RUNNER_21", "RUNNER_22", "RUNNER_3", "RUNNER_4", "RUNNER_5", "RUNNER_8")
}))

