package NuGet_Kotlin_Miruken.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.FinishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'd8420070-ca13-4e71-886c-72d00f96d535_MirukenMediateCastle_DeployPreRelease' (id = 'NuGet_Kotlin_Miruken_MirukenMediateSln_MirukenMediateCastle_DeployPreRelease')
accordingly and delete the patch script.
*/
changeBuildType("d8420070-ca13-4e71-886c-72d00f96d535_MirukenMediateCastle_DeployPreRelease") {
    triggers {
        val trigger1 = find<FinishBuildTrigger> {
            finishBuildTrigger {
                buildTypeExtId = "NuGet_Kotlin_Miruken_MirukenMediateSln_PreReleaseBuild"
                successfulOnly = true
                branchFilter = "+:*"
            }
        }
        trigger1.apply {
            enabled = false
        }
    }
}
