package NuGet_Kotlin_Improving.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '1852e351-879e-426d-9bb7-299060589c6f_CIBuild' (id = 'NuGet_Kotlin_Improving_ImpHghwyDtScp_CIBuild')
accordingly and delete the patch script.
*/
changeBuildType("1852e351-879e-426d-9bb7-299060589c6f_CIBuild") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
