package NuGet_Kotlin_Improving.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.BuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '1852e351-879e-426d-9bb7-299060589c6f_ImprovingHighwayDataScope_DeployRelease' (id = 'NuGet_Kotlin_Improving_ImpHghwyDtScp_ImprovingHighwayDataScope_DeployRelease')
accordingly and delete the patch script.
*/
changeBuildType("1852e351-879e-426d-9bb7-299060589c6f_ImprovingHighwayDataScope_DeployRelease") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    expectSteps {
        step {
            name = "NuGet Pack for NuGet.org"
            type = "jb.nuget.pack"
            param("nuget.pack.include.sources", "true")
            param("nuget.pack.output.clean", "true")
            param("nuget.pack.output.directory", "nupkg")
            param("nuget.pack.prefer.project", "true")
            param("nuget.pack.specFile", "%NuGetPackSpecFiles%")
            param("nuget.pack.version", "%PackageVersion%")
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("toolPathSelector", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
        }
        step {
            name = "Nuget Publish to NuGet.org"
            type = "jb.nuget.publish"
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nuget.publish.files", "nupkg/%NupkgName%")
            param("nuget.publish.source", "nuget.org")
            param("secure:nuget.api.key", "%ImprovingNugetApiKey%")
            param("toolPathSelector", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
        }
        step {
            name = "Nuget Publish to SymbolSource.org"
            type = "jb.nuget.publish"
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nuget.publish.files", "nupkg/%NupkgSymbolsName%")
            param("nuget.publish.source", "https://nuget.smbsrc.net/")
            param("secure:nuget.api.key", "%ImprovingNugetApiKey%")
        }
    }
    steps {
        update<BuildStep>(1) {
            param("secure:nuget.api.key", "credentialsJSON:f6c68349-8598-4833-90ca-a92cecf8064c")
        }
        update<BuildStep>(2) {
            param("secure:nuget.api.key", "credentialsJSON:f6c68349-8598-4833-90ca-a92cecf8064c")
        }
    }
}
