package NuGet_Kotlin_Improving.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '444fa27c-654b-4804-81bb-89c1babd42ce_ImprovingDbUpQuickStart_DeployPreRelease' (id = 'NuGet_Kotlin_Improving_ImprovingDbUp_ImprovingDbUpQuickStart_DeployPreRelease')
accordingly and delete the patch script.
*/
changeBuildType("444fa27c-654b-4804-81bb-89c1babd42ce_ImprovingDbUpQuickStart_DeployPreRelease") {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
